# Spring全局配置
spring:
    profiles:
        # 引用product配置参数,本地开发配置-Dspring.profiles.active=local即可覆盖当前参数
        #org.springframework.boot.context.config.ConfigFileApplicationListener.ACTIVE_PROFILES_PROPERTY
        active: product
        # 包含配置参数
        #org.springframework.boot.context.config.ConfigFileApplicationListener.INCLUDE_PROFILES_PROPERTY
        #include: mysql

    # 数据库连接池配置
    datasource:
        driverClassName: org.sqlite.JDBC
        # "jdbc:sqlite::memory:"
        url: jdbc:sqlite:oauth2.db
        schema: classpath:sql/schema-sqlite.sql
        #data: classpath:sql/sqlite-data.sql
        initialize: true

        tomcat:
            initialSize: 5
            maxActive: 60
            maxIdle: 10
            minIdle: 5
            maxWait: 5000
            testWhileIdle: true
            validationQuery: SELECT 1
            validationQueryTimeout: 10
            validationInterval: 3000
            timeBetweenEvictionRunsMillis: 3100
            minEvictableIdleTimeMillis: 120000
            numTestsPerEvictionRun: 10
            removeAbandoned: true
            removeAbandonedTimeout: 180
            defaultAutoCommit: false

    # JSON配置
    jackson:
        # 蛇形命名
        propertyNamingStrategy: SNAKE_CASE

        serialization:
            # 关闭为null的对象抛出异常，解决懒加载
            FAIL_ON_EMPTY_BEANS: false
            # 开启格式化输出JSON，默认没有换行
            #INDENT_OUTPUT: true

        deserialization:
            # 关闭未知属性抛出异常，忽略JavaBean中没有的属性
            FAIL_ON_UNKNOWN_PROPERTIES: false
            # 将空串("")转换为null
            ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true

        # 不将空属性值写入JSON
        defaultPropertyInclusion: NON_EMPTY

        # mapper: # com.fasterxml.jackson.databind.MapperFeature

        parser:
            # 允许属性名称没有引号包裹
            ALLOW_UNQUOTED_FIELD_NAMES: true
            # 允许属性名称使用单引号('')包裹
            ALLOW_SINGLE_QUOTES: true
            # 允许出现特殊字符和转义字符，小于32的ASCII
            ALLOW_UNQUOTED_CONTROL_CHARS: true

        # generator: # com.fasterxml.jackson.core.JsonGenerator

    # HTTP配置
    http:
        encoding:
            # 设置字符集
            charset: UTF-8
            # 强制请求, 响应都设置, 默认只设置请求
            force: true
        converters:
            preferred-json-mapper: jackson

    # MVC配置
    mvc:
        throw-exception-if-no-handler-found: true
        favicon:
            enabled: false

mybatis:
    mapperLocations: classpath*:dao/I**DAO.xml

pagehelper:
    # 指定使用数据库
    #dialect: com.github.pagehelper.dialect.helper.MySqlDialect
    # 进行count查询
    rowBoundsWithCount: true
    # 是否进行合理化查询, pageNum<1, pageNum>pages
    reasonable: true

# HTTP服务器配置
server:
    port: 8080
    error:
        whitelabel:
            enabled: false

# 应用管理配置
management:
    # 管理服务限制访问ip
    address: 127.0.0.1
    # 管理服务端口
    port: 9999
    # 服务管理地址前缀
    context-path: /manager
    # 应用程序安全认证
    security:
        # 开启认证
        enabled: true

# org.springframework.boot.actuate.endpoint.mvc.ShutdownMvcEndpoint
endpoints:
    # 是否安全验证,如果开启需要配合spring安全框架
    sensitive: true
    # 关闭应用配置
    shutdown:
        # 启动关闭应用
        enabled: true
        # 设置关闭应用访问路径
        path: /shutdown

# 配置安全认证信息
security:
    basic:
        # 针对指定路径前缀启用安全验证
        path: /manager
    user:
        name: admin
        password: admin
