SET AUTOCOMMIT = 0;
START TRANSACTION;

-- 插入用户信息
INSERT INTO T_OAUTH2_USER (ID, MOBILE, EMAIL, USERNAME, PASSWORD, STATUS, NICKNAME, HEAD_IMG_URL, SEX, COUNTRY, PROVINCE, CITY, CREATION_TIME) VALUES (REPLACE(UUID(),'-',''), NULL, NULL, 'admin', '123456', 0, '管理员', NULL, NULL, NULL, NULL, NULL, 0);
-- 插入客户信息
INSERT INTO T_OAUTH2_CLIENT (ID, NAME, CLIENT_ID, CLIENT_SECRET, CLIENT_URI, REDIRECT_URI, DESCRIPTION, ICON_URI, EXPIRES_IN, CREATION_TIME) VALUES (REPLACE(UUID(),'-',''), '测试', 'test', 'test', 'http://127.0.0.1', 'http://127.0.0.1', '测试凭证', NULL, -1, 0);

COMMIT;
SET AUTOCOMMIT = 1;
